### ISSUE TITLE
Payment form not showing

### ISSUE THREAD

**Issue by matteocuellarvega** [webong/plugin-paystack-memberpress#2]
I've tried looking through the code and debugging it, however I can't seem to seem to figure it out. No payment details are captured on the payment page. It only shows the invoice/total and a payment button. When you press Pay it only shows the following error: ERROR: A validation error has occured. Any help would be greatly appreciated.

**Comment by matteocuellarvega** [comment]
@webong Hey, I've figured out what the issue is. In MeprPaystackGateway.php on line 1279 it sets the years interval to "yearly", however the Paystack API expects "annually" (https://developers.paystack.co/v2.0/docs/subscriptions).

 I would clone, fix and push the fix, however I'm not well versed in git procedures...

**Comment by webong** [comment]
Hello @matteocuellarvega ... Thanks for spotting the issue ... If you don't mind ... I can quickly make the fix and update the repository.

**Comment by matteocuellarvega** [comment]
No wahala. Go ahead. Thanks for creating this plugin!

**Comment by webong** [comment]
Hey @matteocuellarvega ... This has been resolved now ... Once again, thank you.
